### PR TITLE
fix synchronization without a date_col

### PR DESCRIPTION
**Pull request by beda42**
When the `date_col` of the clickhouse model is set to `None`, the synchronization code crashes as it does not really expect this to happen (`TypeError: getattr(): attribute name must be string` in engines.py at `obj_date = getattr(obj, date_col)`).

This PR fixes the problem for me with minimum effort.

It is still missing tests.

### CODE REVIEW

**Comment by M1ha-Shvn** [comment]
Hi
This is an interesting case.
If I understand correctly, you use `partition_key` other than `toYYYYMM(date_col)` and so there is no `date_col` in your code?

The main problem with your PR code is that it is not effective:
1. `FINAL` modifier makes ClickHouse to collapse all rows by primary key during request, which would cause very slow performance on big amounts of data. This is the reason, I've made alternative `_get_final_versions_by_version` method which works fast, though is not so obvious in usage.
2. `date_col` filter also adds performance to the query. Without it ClickHouse have to fetch all data stored on the disc, instead of taking only data used by the query.  

From my point of view, the correct way of handling here is not removing date filter at all, but replacing it with other one, based on `partition_key`. We can not do it for any case: I don't really know, what fields `partition_key` relies on and how can we use them to speed up this query.
It seems, that better solution is to raise exception or warning, when date_col is not provided and suggest to redeclare get_final_versions method...

**Comment by M1ha-Shvn** [comment]
I'll make a change, by which if date column is not set, date filter would not be added to final versions queries and a warning of inefficiency would be generated. Does it suit your needs?

**Comment by beda42** [comment]
Hi,

thanks for the quick reply.

Yes, I have data that does not use partitioning based on date, but rather on an integer column. Also when new data is added or deleted, it does not necessarily have the same partitioning key.

I solve the issue of finding the objects by ID by adding an index of type set to this column in clickhouse. I was not able to test this approach with django-clickhouse yet, but it worked for me when trying a different approach to django->clickhouse synchronization.

So yes, simply working without the `date_col` and issuing a warning would be OK with me. Just let me shoot myself into the leg if I want to ;)

**Comment by M1ha-Shvn** [comment]
Released [v1.1.2](https://github.com/carrotquest/django-clickhouse/releases/tag/v1.1.2)

**Pull request closed without merging**
